### ISSUE TITLE
Question about article Don't Be Scared of git rebase

### ISSUE THREAD

**Issue by brutalcrozt** [nathanleclaire/blog#41]
[here](https://github.com/nathanleclaire/blog/blob/master/content/post/dont-be-scared-of-git-rebase.markdown#a-word-on-re-writing-history) on 
> NEVER EVER force push to a remote where other people are working unless:

After reading that that makes me afraid to force push, i don't know what the implication. Would you explain it to me please?  @nathanleclaire

**Comment by nathanleclaire** [comment]
@brutalcrozt 

If you force push to a branch that _you_ are the only one using, it's fine. (You should still double check first to make sure it will have the intended result) This is frequently done in instances like when you have a pending PR, where the reviewer has asked you to make some changes, but adding a bunch of commits like "Change classname", "Fix typo", etc. doesn't make sense. You can keep the history clean / how you'd like it to show up long-term (upstream) this way. For instance, I usually keep a `git remote` called `nathan` that I use when contributing to upstream projects -- `origin` would be something like `git@github.com:moby/moby` and `nathan` would be something like `git@github.com:nathanleclaire/moby`. I can force push to `nathan` all day without fear that I'll interfere with someone else's work. The same couldn't be said of `origin`.

If you force push to a branch that is _shared_ you run the risk of erasing someone else's work completely. There might be commits on that branch that you do not have on your local copy and thus over-write. That's bad, of course. This is what I reference in the article. Hope this helps
